apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: socks-ingress
  annotations:
    kubernetes.io/ingress.global-static-ip-name: "{{ .Values.frontend.ip }}"
    kubernetes.io/ingress.class: "gce"
spec:
  rules:
  - http:
      paths:
      - path: /*
        backend:
          serviceName: front-end
          servicePort: 80
